# Generated by Django 3.1.5 on 2021-01-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('datum', models.DateField(auto_now_add=True)),
                ('opis', models.TextField()),
                ('vrstaLinije', models.CharField(choices=[('dnevna', 'dnevna'), ('noćna', 'noćna'), ('vanredna', 'vanredna')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='stajaliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('naselje', models.CharField(max_length=200)),
                ('datum', models.DateField(auto_now_add=True)),
                ('opis', models.TextField()),
                ('duzina', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sirina', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
