# Generated by Django 3.1.5 on 2021-01-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('night_line', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='linija',
        ),
        migrations.DeleteModel(
            name='stajaliste',
        ),
        migrations.AddField(
            model_name='line',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='peron.station'),
        ),
        migrations.AddField(
            model_name='line',
            name='middle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle', to='peron.station'),
        ),
        migrations.AddField(
            model_name='line',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='peron.station'),
        ),
    ]
